FROM  mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 9000
    
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build 

WORKDIR /src
COPY ./src/ .

WORKDIR /src/api-gateway
RUN dotnet publish "./api-gateway.csproj" -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "api-gateway.dll"]
