FROM node:22.21-alpine AS build
WORKDIR /app

RUN npm install -g npm@latest
RUN npm install -g @angular/cli@20.1.5

COPY package*.json ./
RUN npm install

EXPOSE 4200
CMD ["npm", "run", "start:docker"]